### PR TITLE
Fixed warnings

### PR DESCRIPTION
**Pull request by Pawapek**
Hi,

I've fixed some warnings but there is still one to deal with. Perhaps you can take a look on it.

In file included from reference.c:24:0:
reference.c: In function ‘ReferenceInitialize’:
macros.h:33:17: warning: variable ‘call_context’ set but not used [-Wunused-but-set-variable]
     OCI_Context call_context;            \
                 ^
macros.h:44:5: note: in expansion of macro ‘CONTEXT’
     CONTEXT(src_type, src_ptr)                             \
     ^~~~~~~
reference.c:41:5: note: in expansion of macro ‘ENTER_FUNC’
     ENTER_FUNC
     ^~~~~~~~~~

### CODE REVIEW

**Comment by vrogier** [comment]
Hi,

Thanks for taking time to propose this PR.
Unfortunately, I can't merge it for 2 reasons:
- I do not yet have put in place Contributor License Agreement (CLA) for OCILIB repository
- I am working on 4.7.1 release (develop-v4.7.1 branch) that has conflicting changes as all internal private symbols have been renamed.

But Idid commit some changes in the branch develop-v4.7.1 that allow to compile OCILIB without any warnings with -Wall -Wextra -Wpedantic flags, at least with gcc 4.x

Can you have a look at the branch and let me know if all warnings are gone for you ? thanks ;)

Regards,

Vincent

**Comment by Pawapek** [comment]
Hi,

thank you for swift answer :) As far I know there are still four warnings. Just for the future, would you like to prepare pull requests for such minor changes or create topic in "Issues" with patch file attached?

1.
>gmake~4.2.1 making:ocilib/linux64/agent_so.o
In file included from ocilib/source/macros.h:24:0,
                 from ocilib/source/agent.c:23:
ocilib/source/error.h:28:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 );
 ^

2.
>In file included from ocilib/source/environment.c:26:0:
ocilib/source/error.h:28:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 );
 ^
ocilib/source/environment.c:557:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 static void OcilibEnvironmentKeyMapFree
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
ocilib/source/environment.c: In function ‘OcilibEnvironmentKeyMapFree’:
ocilib/source/environment.c:557:13: warning: old-style function definition [-Wold-style-definition]

3.
>gmake~4.2.1 making:ocilib/linux64/handle_so.o
In file included from ocilib/source/macros.h:24:0,
                 from ocilib/source/handle.c:23:
ocilib/source/error.h:28:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 );
 ^
ocilib/source/handle.c: In function ‘OcilibHandleGetEnvironment’:
ocilib/source/handle.c:29:14: warning: old-style function definition [-Wold-style-definition]
 const void * OcilibHandleGetEnvironment
              ^~~~~~~~~~~~~~~~~~~~~~~~~~

4.
> gmake~4.2.1 making:ocilib/linux64/pool_so.o
In file included from ocilib/source/ocilib.c:35:0:
ocilib/source/error.h:28:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 );
 ^
ocilib/source/ocilib.c:61:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 static void OcilibCheckContext()
             ^~~~~~~~~~~~~~~~~~
ocilib/source/ocilib.c: In function ‘OcilibCheckContext’:
ocilib/source/ocilib.c:61:13: warning: old-style function definition [-Wold-style-definition]
In file included from ocilib/source/macros.h:24:0,
                 from ocilib/source/pool.c:25:
ocilib/source/error.h:28:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 );
 ^

**Comment by vrogier** [comment]
Ok, I will fix these also and commit asap.
What is your GCC version ?

**Comment by vrogier** [comment]
hi,

commit 8d038741 addresses  -Wstrict-prototypes

**Comment by Pawapek** [comment]
Hi,

thanks for addressing this issue :), warnings are gone.
I'm using GCC 7.3.1 20180303.

**Pull request closed without merging**
